version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      nextjs:
        patterns:
          - 'next'
          - '@next/*'
          - 'eslint-config-next'
      eslint-prettier:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'
        exclude-patterns:
          - 'eslint-config-next'
      react:
        patterns:
          - '@types/react*'
          - 'react'
          - 'react-*'
      misc:
        patterns:
          - '*'
        exclude-patterns:
          - 'next'
          - '@next/*'
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'
          - '@types/react*'
          - 'react*'

  - package-ecosystem: cargo
    directory: '/backend/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      axum:
        patterns:
          - 'axum-*'
      shuttle:
        patterns:
          - 'shuttle-*'
